// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compile(arg1) {
  return window['go']['main']['App']['Compile'](arg1);
}

export function CompilerInfo() {
  return window['go']['main']['App']['CompilerInfo']();
}

export function CurrentFileName() {
  return window['go']['main']['App']['CurrentFileName']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function KillProcess() {
  return window['go']['main']['App']['KillProcess']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}
