// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {compiler} from '../models';

export function Compile(arg1:string):Promise<void>;

export function CompilerInfo():Promise<compiler.Info>;

export function CurrentFileName():Promise<string>;

export function IsRunning():Promise<boolean>;

export function KillProcess():Promise<void>;

export function OpenFile():Promise<string>;

export function SaveFile(arg1:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<void>;

export function SendInput(arg1:string):Promise<void>;
